CREATE SEQUENCE IF NOT EXISTS account_sequence START WITH 10000000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS customer_entity (
    customer_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    pan VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_account (
    account_id BIGINT PRIMARY KEY DEFAULT nextval('account_sequence'),

    customer_id BIGINT NOT NULL,
    account_holder_name VARCHAR(255),

    account_type VARCHAR(50),
    balance DOUBLE PRECISION,
    interest_rate DOUBLE PRECISION,

    account_status VARCHAR(50),

    last_transaction_timestamp TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_bank_customer
        FOREIGN KEY (customer_id)
            REFERENCES customer_entity(customer_id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id UUID PRIMARY KEY,

    from_account_id BIGINT,
    to_account_id BIGINT,

    amount DOUBLE PRECISION NOT NULL,
    initial_balance DOUBLE PRECISION NOT NULL,
    remaining_balance DOUBLE PRECISION NOT NULL,

    transaction_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,

    CONSTRAINT fk_from_account
        FOREIGN KEY (from_account_id)
            REFERENCES bank_account(account_id),

    CONSTRAINT fk_to_account
        FOREIGN KEY (to_account_id)
            REFERENCES bank_account(account_id)
);
